### ISSUE TITLE
How to assemble

### ISSUE THREAD

**Issue by emeb** [WillStevens/basic1K#1]
Could you please include some text in the README.md about how to assemble this source? Specifically which 8080 macro assembler you're targeting - I've tried several different ones and haven't been successful yet due to syntax variations.

**Comment by WillStevens** [comment]
Hi Eric

I’ve added details in the instructions - I used this online assembler:

<https://www.asm80.com/onepage/asm8080.html>


best wishes, Will

**Comment by emeb** [comment]
Thanks!
